### PR TITLE
* send unsupported image files as document - Fix #552

### LINKED ISSUE #552: Problem when sending unsupported image files
Related to #532 , when sending an unsupported image file with "image/*" mime type, a problem occurs. 

I've tried to solve it on whatsapp-web.js but maintainers suggested to force send as document when the image is unsupported.

I'll send a pull request soon that will force send as document if filename is an image but isn't a file with jpeg/png/gif extension.

### PR DESCRIPTION
**Pull request by allgood**

### CODE REVIEW

**Comment by alicompu** [comment]
Hi, 
Please say an example?

**Comment by allgood** [comment]
> Hi, Please say an example?

Hi @alicompu ,

dwg files from autocad have an "image/*" mimetype but is not supported by whatsapp, so it gives an error when trying to send it.

This can occur with other filetypes

**Comment by alicompu** [comment]
@allgood 
Okay I understand.
Thank you 🙏

**Comment by allgood** [comment]
@canove , please evaluate merging this. It is really impossible to send .dwg files through whaticket without this change

**Comment by eigonsouza** [comment]
Hello everyone, what about coreldraw files, .cdr extension? Would you have any idea how to recognize this extension in document format?

I'm trying to create something, but the mime type doesn't have the .cdr extension coreldraw

**Pull request merged**
